---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины

non-functional:
- Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен иметь мобильную версию
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
- Сайт должен быть способен обрабатывать большое количество трафика
- Сайт должен быть доступен на различных устройствах

implicit:
- Должна быть кнопка быстрого перехода вверх к началу списка отображаемых товаров, когда пользователь находится внизу этого списка
- На главной странице отображать панель "Хиты продаж"
- При наведении на товар в списке его иконка должна явно выделять своё отображение относительно других товаров в списке
- В поле "Поиск" ("Search") расположить иконку лупы для наглядности
- Должна быть возможность быстрого просмотра товара на странице списка товаров без перехода к подробной информации о нем
- В выпадающем меню Language/Язык активный вариант языка веб-приложения должен выделяться относительно других (неактивных в текущее время)
